// Code generated by hertz generator.

package hello_service

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/common/config"
	"github.com/cloudwego/hertz/pkg/protocol"
	thriftgo_example "thirft_client/model/thriftgo_example"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type Client interface {
	HelloMethod(context context.Context, req *thriftgo_example.HelloReq, reqOpt ...config.RequestOption) (resp *thriftgo_example.HelloResp, rawResponse *protocol.Response, err error)

	OtherMethod(context context.Context, req *thriftgo_example.OtherReq, reqOpt ...config.RequestOption) (resp *thriftgo_example.OtherResp, rawResponse *protocol.Response, err error)
}

type HelloServiceClient struct {
	client *cli
}

func NewHelloServiceClient(hostUrl string, ops ...Option) (Client, error) {
	opts := getOptions(append(ops, withHostUrl(hostUrl))...)
	cli, err := newClient(opts)
	if err != nil {
		return nil, err
	}
	return &HelloServiceClient{
		client: cli,
	}, nil
}

func (s *HelloServiceClient) HelloMethod(context context.Context, req *thriftgo_example.HelloReq, reqOpt ...config.RequestOption) (resp *thriftgo_example.HelloResp, rawResponse *protocol.Response, err error) {
	httpResp := &thriftgo_example.HelloResp{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{
			"name": req.GetName(),
		}).
		setPathParams(map[string]string{}).
		setHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("GET", "/hello")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

func (s *HelloServiceClient) OtherMethod(context context.Context, req *thriftgo_example.OtherReq, reqOpt ...config.RequestOption) (resp *thriftgo_example.OtherResp, rawResponse *protocol.Response, err error) {
	httpResp := &thriftgo_example.OtherResp{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		setHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("POST", "/other")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

var defaultClient, _ = NewHelloServiceClient("")

func ConfigDefaultClient(ops ...Option) (err error) {
	defaultClient, err = NewHelloServiceClient("", ops...)
	return
}

func HelloMethod(context context.Context, req *thriftgo_example.HelloReq, reqOpt ...config.RequestOption) (resp *thriftgo_example.HelloResp, rawResponse *protocol.Response, err error) {
	return defaultClient.HelloMethod(context, req, reqOpt...)
}

func OtherMethod(context context.Context, req *thriftgo_example.OtherReq, reqOpt ...config.RequestOption) (resp *thriftgo_example.OtherResp, rawResponse *protocol.Response, err error) {
	return defaultClient.OtherMethod(context, req, reqOpt...)
}
